### ISSUE TITLE
Vaadin 7.5.5 js issue

### ISSUE THREAD

**Issue by gokhanoner** [downdrown/VaadinHighChartsAPI#13]
I implemented pieChart example. I cannot see anything on the screen. When I look to the logs, I see this:

```
:9191/vaadinServlet/APP/PUBLISHED/exporting.js:263 Uncaught ReferenceError: Highcharts is not defined
:9191/vaadinServlet/APP/PUBLISHED/funnel.js:92 Uncaught ReferenceError: Highcharts is not defined
:9191/vaadinServlet/APP/PUBLISHED/heatmap.js:274 Uncaught ReferenceError: Highcharts is not defined
:9191/vaadinServlet/APP/PUBLISHED/highcharts-more.js:745 Uncaught ReferenceError: Highcharts is not defined
```

any idea?

**Comment by DavidBrehm2** [comment]
I had the same problem - I think the JS load order in HighChart.java is wrong:

@JavaScript({"jquery-2.1.3.min.js", "exporting.js", "funnel.js", "heatmap.js", "highcharts-more.js", "highcharts.js", "highcharts-connector.js"})

The load order should be:
@JavaScript({"jquery-2.1.3.min.js", "highcharts.js",  "exporting.js", "funnel.js", "heatmap.js", "highcharts-more.js", "highcharts-connector.js"})

EDIT:
Ok tried it out and the only way I could get it to work in Firefox was without the heatmap.js
No JS Error is thrown.

So Chrome(47.0.2516.0 dev-m):
@JavaScript({"jquery-2.1.3.min.js", "highcharts.js",  "exporting.js", "funnel.js", "heatmap.js", "highcharts-more.js", "highcharts-connector.js"}) 
works
Firefox (41.0):
@JavaScript({"jquery-2.1.3.min.js", "highcharts.js",  "exporting.js", "funnel.js", "highcharts-more.js", "highcharts-connector.js"})
works

**Comment by gokhanoner** [comment]
How did you make it worked ?

**Comment by DavidBrehm2** [comment]
You have to change the HighChart.java file. (Or extend AbstractHighChart and adjust the Annotation)

But there is another Issue #14 so you may want to wait until these issues are fixed here.

From what I see on Vaadin Addons the author Manfred Huber is very responsive so I would give it a few days :) 
If it is a time critical issue I can give you more details.

**Comment by gokhanoner** [comment]
Ahh, I can wait a couple of days, no problem :)

**Comment by downdrown** [comment]
I am very sorry that I haven't replied till now! I was few days on vacation and had no time for my Laptop!
This bug is a bad thing... But as I can see you guys were that nice and gave me the solution already! I have nearly no time to test my Addon and so such crap can happen (Sorry 🙈) I will solve this bug as soon as possible and re-publish this version! Thank you for your interest!

**Comment by DavidBrehm2** [comment]
No Problem - this is a record response time :)
I really like the addon!

**Comment by downdrown** [comment]
So I just tried to run it with my "old" JavaScript annotation and it worked fine for me!
(Firefox 40.0.2 & IE 10.0.9200.17267)

Maybe this error occured because of bug #14 !!?

![screen](https://cloud.githubusercontent.com/assets/3913600/10185396/ef47d2c4-6747-11e5-8602-08c188d92af2.PNG)

**Comment by downdrown** [comment]
I commited the latest changes and it would be helpful if you could just fetch these, compile it local and re-try it with this version - so that i can be sure the bug is fixed now!

**Comment by DavidBrehm2** [comment]
Ok tried it out with the different annotation order - did not work.
ReferenceError: Highcharts is not defined
Are you sure you don't include Highcharts globally somewhere in your TestProject or have your JS files cached by the browser?

Maybe it is a special bug with my project setup. It seems to load all JS Files twice so that is strange.

From the Firefox Console:
@JavaScript({"jquery-2.1.3.min.js", "exporting.js", "funnel.js", "heatmap.js", "highcharts-more.js", "highcharts.js", "highcharts-connector.js"})
![highchart](https://cloud.githubusercontent.com/assets/13018905/10189195/16765aa6-6765-11e5-998d-46a4125bf905.png)
@JavaScript({"jquery-2.1.3.min.js", "highcharts.js",  "exporting.js", "funnel.js", "highcharts-more.js", "highcharts-connector.js"})
![highchart2](https://cloud.githubusercontent.com/assets/13018905/10189196/19b98cf6-6765-11e5-8c4a-cdccc7fc5b79.png)

**Comment by downdrown** [comment]
Pretty strange! - No I disabled caching for development, well I am not sure where this problem comes from... as I told you for me everything works fine! 

Please get [this](https://github.com/downdrown/VaadinHighChartsAPI-Demo) project and try to comple and run it locally - I tried it with this project my own! 
Take care you are using the latest build in the pom.xml!

**Comment by DavidBrehm2** [comment]
Jep same problem.
Are you sure you are using the remaining-chart-types branch HighChart.java file - and not a cached one from the main branch?
Are the JS Files loaded in your dev-project - can you confirm the load order from the console?
![highchart3](https://cloud.githubusercontent.com/assets/13018905/10191069/55069428-6771-11e5-9233-493415f04e87.png)

**Comment by downdrown** [comment]
You're right, the js files are loaded twice on each request!

![jsload](https://cloud.githubusercontent.com/assets/3913600/10191437/31a4de10-6774-11e5-8311-4ee0d36213f7.PNG)

But that doesn't explain why I can draw the diagram without any error...
And yes, **remaining-chart-types** is my currently active branch!

I have to admit, that i have no idea at the moment...

**Comment by DavidBrehm2** [comment]
Well in a browser with active cache that wouldn't really matter. 
The load order is clearly wrong though:

> To enable exporting, the module needs to be included, it can be downloaded from >http://code.highcharts.com/ and included after highcharts.js or highstock.js. 

(from http://www.highcharts.com/docs/export-module/export-module-overview)

If you look at the JS files the global Highcharts namespace has to be defined first.
Then it can be used by the modules.
So highcharts.js has to be loaded first.

**Comment by downdrown** [comment]
I changed the loading order like this:

``` java
@JavaScript({"jquery-2.1.3.min.js", "highcharts.js", "highcharts-more.js", "funnel.js", "heatmap.js", "exporting.js", "highcharts-connector.js"})
```

Should do it, what do you think?

**Comment by downdrown** [comment]
Tried it... I get no more "Reference Error"

![konsole](https://cloud.githubusercontent.com/assets/3913600/10191907/953415e6-6778-11e5-9536-6280af9e9164.PNG)

Could you be that nice and try it once again in your environment with the correct loading-order?

**Comment by DavidBrehm2** [comment]
Yes that should work - that is what I have in my production environment.
Sorry I cannot really test it in your example project - not really sure where maven keeps the libs.
We use gradle :). I will test as soon as the git-repository is updated.
I am not sure why I get the problem with heatmap.js but will investigate further.
Maybe we can get @gokhanoner to confirm?

**Comment by downdrown** [comment]
I will just publish it I think - the community will test it anyway! Many thanks for your support!

**Comment by gokhanoner** [comment]
If you can publish it, I'll test & confirm immediately.

**Comment by downdrown** [comment]
Just released it on Vaadin's Addon-Directory!

**Comment by gokhanoner** [comment]
It's working, thanks for your help.. Now I can make some fancy stuff :)

![image](https://cloud.githubusercontent.com/assets/6715308/10193372/54d0169a-678b-11e5-8eb2-cf1c973c6cac.png)

**Comment by downdrown** [comment]
Great! Have much fun using it! 😁👍🏻

**Comment by gokhanoner** [comment]
Thanks. 2 simple questions:
- How did you disable export button ?
- Does it support modifyting label ? (Like data + percentege etc.)

**Comment by DavidBrehm2** [comment]
Exporting Options are not in the JavaAPI yet:
http://api.highcharts.com/highcharts#exporting.enabled
You could remove the exporting.js from the HighChart.java to disable them.
So that would be a temporary fix.

I guess you mean the tooltip (popup) label?
That is also not in yet.
http://api.highcharts.com/highcharts#tooltip
You would either define a tooltip formatter or define the valueSuffix property.

So I guess you can make a fork and implement this stuff :)
I will be working with this addon for a while so I guess I will do just that for stuff that I need that is missing.
What do you think @downdrown  -  what are your next plans for the projekt?

**Comment by gokhanoner** [comment]
Yep, I think I can do it ;)

**Comment by DavidBrehm2** [comment]
Hm maybe to be more expandable the ChartConfiguration could implement an interface with

```
String getHighChartValue();
```

So we could use the HighchartFactory and AbstractHighChart with our own ChartConfiguration?
So you don't have to implement every little detail in the highchart api.
EDIT:
The problem with that is all the serialization that goes on in getHighChartValue() - and cant be broken into different parts that easily. 
So maybe a property - additionalOptions with an Interface 

```
String getHighChartValue();
```

that gets added to the option String.

Hm maybe a bad idea as this would require a deeper knowledge of the highcharts api and the serialization in general - so adding to the JavaAPI seems to be the way to go :)

**Comment by downdrown** [comment]
I think I understand what you mean, but as you mentioned it's a bit problematically WHERE to put the serialized highcharts value! So I basically think it's more easy to write the most practically options directly into the API and give up some additional features!

Recently I found a already finished Java API for HighCharts and thought of implementing it into my Project, but I think at this point I am already to far to make a restart!
It would generally change the whole workflow of how to use this addon, so I prefer to build it on my own...

**Comment by DavidBrehm2** [comment]
I think you made a lot of good decisions on the API -  it is not that easy to keep the flexibility of the Highcharts Options in a Java API. 
The really difficult part is the series implementation and from what I saw that is really well done.
The only missing stuff is implementing more of the options.
EDIT: Maybe you could consider adding html legends. (table linked to the chart)
It is one area where Highcharts is not really that good but I think they are important in a business application.
