### ISSUE TITLE
HighChartsPlotOptionsImpl.Steps 'FALSE' does not work

### ISSUE THREAD

**Issue by YeTingGe** [downdrown/VaadinHighChartsAPI#22]
ChartType.LINE is displayed as steps.

HighChartsPlotOptionsImpl.Steps 'FALSE' does not work, should be "step: false" instead of "step: 'FALSE' "

**Comment by mes-07** [comment]
Hi,

I have the same problem.
The Highcharts API documentation says that by default it should show the direct connections between the dots in the line chart without any steps.
So at first I didn't configure anything and left it as it is and thought it will use the default value.

Since that didn't work out, I tried it with:
"linePlotOptions.setSteps(Steps.FALSE);" as well

And that didn't work out either...

Also when I want to use "List<Object> sweetValues = new ArrayList<Object>();" as a variable for the values which I want to show in the line chart, Eclipse tells me that this is wrong and that I am supposed to use "List<HighChartsData> sweetValues = new ArrayList<>();"

Is there any possibility that the plotOption is not working because of this different type of variable?

Thanks.

**Comment by downdrown** [comment]
Fixed. Release Outstanding.
